# Generated by Django 2.1.4 on 2018-12-30 19:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('recipes', '0003_auto_20181223_0026'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ('-created',)},
        ),
        migrations.AlterModelOptions(
            name='ingredient',
            options={'ordering': ('-created',)},
        ),
        migrations.AlterModelOptions(
            name='recipe',
            options={'ordering': ('-created',)},
        ),
        migrations.AddField(
            model_name='recipe',
            name='owner',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='recipes', to=settings.AUTH_USER_MODEL),
        ),
    ]
